# Generated by Django 5.0.3 on 2024-03-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursultan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queston",
            name="answer",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="queston",
            name="option3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="queston",
            name="option4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
