# Generated by Django 5.0.3 on 2024-03-31 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursultan", "0002_alter_queston_answer_alter_queston_option3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
