# Generated by Django 5.0.3 on 2024-04-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursultan", "0003_test_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="description",
            field=models.CharField(blank=True, default=" ", max_length=255, null=True),
        ),
    ]
